# Generated by Django 5.0.4 on 2025-01-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
