# Generated by Django 4.2.5 on 2025-01-05 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saloon', '0005_alter_review_options_alter_review_user_servicereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reviews', to='saloon.service'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('service', 'user')},
        ),
    ]
