# Generated by Django 4.2.5 on 2025-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloon', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
