# Generated by Django 4.2.5 on 2025-01-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_review_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
